<a href="https://colab.research.google.com/github/Ritu-95/python_code/blob/main/K_NN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:

#Reading the dataset
dataset  = sns.load_dataset('iris')
#df = pd.read_csv('filename.csv')


In [3]:

#Checking the data
dataset.head(5)
dataset.species.value_counts()
len(dataset)
dataset.info()
dataset.describe()
#EDA Steps


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:


X = dataset.iloc[:, [0,1,2,3]].values
y = dataset.species.values

#Splitting the data into training & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)



In [5]:

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Feature Engineering Steps


#Call the Classifier
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=41)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


#Classification Metrics - To check the final results
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

result1 = accuracy_score(y_test, y_pred)
print('Accuracy is: ', result1*100)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is:  92.10526315789474
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       0.80      1.00      0.89        12
   virginica       1.00      0.77      0.87        13

    accuracy                           0.92        38
   macro avg       0.93      0.92      0.92        38
weighted avg       0.94      0.92      0.92        38

[[13  0  0]
 [ 0 12  0]
 [ 0  3 10]]
